### PR TITLE
Swift 3 Migration

### PR DESCRIPTION
**Pull request by mfk-ableton**
ping @benzguo 

Migrated the Framework to Swift 3.
Might be worth having a more in-depth look at the changes, but it now compiles without warnings and runs all tests, although I had to do a minor change to the PitchSetTest which might be worth looking at more closely.

### CODE REVIEW

**Review by 0thernet — APPROVED** [review]
awesome, thanks for tackling this! (and sorry I haven't really been maintaining this project). ooc, what are you using it for?

**Comment by mfk-ableton** [comment]
Sweet!
I'm working on a little project of my own in my spare time for scale-based midi input, mostly to try to learn swift. Which is why I guess it's worth looking at the individual fixes, although everything works well I'm not sure all of it is best practice or correct (e.g. https://github.com/benzguo/MusicKit/pull/39/commits/9be449afbebdc2abce8fcc86f1a9696b52fcb786)

**Comment by 0thernet** [comment]
ah right, collections have changed. thanks for pointing that out – looks fine to me. I should really do a full audit of the collection implementations; swift has changed a lot since i wrote this stuff.

**Comment by 0thernet** [comment]
also, sounds like a cool project! the chaos harmonizer sample project might be of interest to you – it takes MIDI input, harmonizes it, and outputs the result on another channel, which you should see in your DAW. 

noticed your username has ableton in it – are you associated with them? (i'm a devoted user :D)

**Comment by mfk-ableton** [comment]
nice! thanks for pointing that out. will check that out.

yeah, i work there :)

**Pull request merged**
